#!/usr/bin/env python3
"""
stack_table.py — emit the README's detector-stack table from the geometry itself.

    python3 scripts/stack_table.py           # markdown, paste into README.md
    python3 scripts/stack_table.py --check   # exit 3 if README.md has drifted

The table is GENERATED, not typed, because a hand-written stack table is a
guaranteed future lie: MX17_Full_Geant's README already carries one, and the
moment a thickness moves in the header the two disagree with nothing to catch
it. This reads shared/MX17ModuleGeometry.hh — the single description both sims
consume — so the table cannot drift from the geometry without --check noticing.

WHERE THE NUMBERS COME FROM. ModuleSpec carries each thickness as a member
default initialiser and AsBuiltSpec() overrides a subset. Both matter: the
as-built ESL is 10 µm from the override, while the amp gap, both kaptons and the
pad copper are only ever the declaration defaults. Reading one and not the other
is exactly the mistake scripts/model/mx17_model.py makes (it hardcodes the
LEGACY 100 µm paste, so its FR4 filler is 246.4 µm instead of the as-built
264.4 µm).

The FR4 filler is a RESIDUAL, not a measurement: the CAD gives one 1.70 mm
number for the whole board body, and everything we think we know is subtracted
from it. Changing any other layer silently changes the FR4 — see
design/NEEDED_INPUTS.md §6.

The lamination adhesive under the ESL kapton is NOT in the header and is
therefore NOT in this table's G4 column. It is a response-model estimate
(response/common/constants.py::GLUE_THICK_UM); the material budget it adds is
~19 µm of acrylic against a 1.70 mm board, but electrically it is 29 % of the
insulator the pads see. See the README note under the table.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

HEADER = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "..", "shared", "MX17ModuleGeometry.hh")
README = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "..", "README.md")
BEGIN = "<!-- BEGIN STACK TABLE (generated by scripts/stack_table.py) -->"
END = "<!-- END STACK TABLE -->"


def parse_spec(path):
    """Declaration defaults, then AsBuiltSpec() overrides on top."""
    src = open(path).read()
    spec = {}
    for m in re.finditer(r"^\s*double\s+(\w+)\s*=\s*([-0-9.eE+*/ ]+);", src,
                         re.M):
        try:
            spec[m.group(1)] = eval(m.group(2), {"__builtins__": {}})
        except Exception:
            pass
    body = re.search(r"inline ModuleSpec AsBuiltSpec.*?\n\}", src, re.S)
    if not body:
        raise SystemExit("AsBuiltSpec() not found — header refactored?")
    for m in re.finditer(r"s\.(\w+)\s*=\s*([-0-9.eE+*/ ]+);", body.group(0)):
        try:
            spec[m.group(1)] = eval(m.group(2), {"__builtins__": {}})
        except Exception:
            pass
    return spec


def _glue_um():
    """The response model's over-pad adhesive estimate, or None if unavailable."""
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    ".."))
    from response.common import constants as C
    return C.GLUE_THICK_UM


def fmt_t(um):
    if um < 1.0:
        return f"{um:.1f} µm"
    if um < 1000.0:
        return f"{um:.0f} µm" if abs(um - round(um)) < 5e-2 else f"{um:.1f} µm"
    return f"{um/1000:g} mm"


def build_rows(s):
    """The stack in beam order, window front face -> support plate back."""
    mesh = 2 * s["meshWire_um"]
    n_cu = 5                                   # pcbCuCoverage has 5 entries
    fr4 = (s["pcbTotal_mm"] * 1000 - mesh - s["amp_um"] - s["paste_um"]
           - s["pcbKapton_um"] - n_cu * s["pcbCu_um"]) / n_cu
    fill = 3.14159265358979 * s["meshWire_um"] / (
        4 * (s["meshWire_um"] + s["meshOpen_um"]))
    R = []
    a = R.append
    a(("Gas window", "Mylar (PET)", s["winMylar_um"], "`GasWindow_Mylar`", ""))
    a(("Gas window coat", "Aluminium", s["winAl_um"], "`GasWindow_Al`",
       "drift side"))
    a(("Window→cathode gas", "chamber gas", s["flangeGap_mm"] * 1000,
       "`WindowGapGas`", "set by the 5 mm flange"))
    a(("Drift cathode", "Kapton", s["cathKapton_um"], "`DriftCathode_Kapton`",
       ""))
    a(("Drift cathode Cu", "Copper", s["cathCu_um"], "`DriftCathode_Cu`",
       "cladding, drift side"))
    a(("**Drift gas** ★", "**chamber gas**",
       s["drift_mm"] * 1000 - s["cathCu_um"], "**`DriftGas`**",
       "kapton back → mesh front = 30.000 mm"))
    a(("Micromesh", "Stainless steel", mesh, "`Micromesh`",
       f"woven {s['meshWire_um']:.0f}/{s['meshOpen_um']:.0f} µm, fill {fill:.3f}"))
    a(("**Amp gas** ★", "**chamber gas**", s["amp_um"], "**`AmpGas`**",
       "bulk pillars Ø0.6 mm on a 4.68 mm grid stand in it"))
    a(("Resistive layer (ESL)", "C/acrylic paste", s["paste_um"],
       "`ResistLayer` + `ESLStrip`",
       "515 strips, 550 µm on 0.8 mm; grooves are `AmpGas`"))
    a(("Coverlay kapton", "Kapton", s["pcbKapton_um"], "`PCB_Kapton`",
       "**the ESL⇄pad insulator** — see the note below"))
    a(("Lamination adhesive", "Acrylic", _glue_um(), "— *not placed*",
       "response-model estimate, not in the header"))
    for i, tag in enumerate(("L3 guard ring", "L4 pads", "L5 Y strips",
                             "L6 X strips", "L7 fan-out")):
        a((f"Cu {tag}", "Copper", s["pcbCu_um"], f"`PCB_Cu_{i+3}`",
           "real 512×512 pattern" if i in (1, 2, 3) else "density-scaled"))
        a((f"FR4 under {tag.split()[0]}", "Epoxy-glass", fr4,
           f"`PCB_FR4_{i+3}`", "**residual** of the CAD 1.70 mm board"))
    a(("Rohacell 51", "PMI foam", 5000.0, "`PCB_Rohacell`", ""))
    a(("Backing mylar", "Mylar (PET)", s["backMylar_um"], "`PCB_BackMylar`",
       "aluminized"))
    a(("Backing Al", "Aluminium", s["backAl_um"], "`PCB_AlFoil`", ""))
    a(("Support plate", "Aluminium", s["plate_mm"] * 1000, "`SupportPlate_Al`",
       f"{s['plateAp_mm']:.0f} mm aperture"))
    return R, fr4


def markdown(s):
    rows, fr4 = build_rows(s)
    out = [BEGIN, "",
           "| Layer | Material | Thickness | G4 volume | Note |",
           "|---|---|---|---|---|"]
    z = 0.0
    for name, mat, t_um, vol, note in rows:
        out.append(f"| {name} | {mat} | {fmt_t(t_um)} | {vol} | {note} |")
        # The adhesive is real but is not a placed volume, so it must not enter
        # a depth that claims to describe the Geant4 stack.
        if "not placed" not in vol:
            z += t_um
    out += ["",
            f"Depths are in beam order from the window front face; the stack "
            f"totals **{z/1000:.3f} mm** to the back of the support plate "
            f"(the readout board body is exactly the CAD **1.700 mm** from "
            f"mesh front to laminate back). Board **{s['pcbFace_mm']:.0f}²**, "
            f"**399.36 mm** readout window. ★ = scored volume.",
            "",
            "**Two cautions about the bottom half of this table.**",
            "",
            "*The FR4 is a residual, not a measurement.* The CAD gives one "
            "1.70 mm number for the whole board body; everything we think we "
            "know is subtracted and the remainder is divided equally over the "
            "five laminate layers. So changing any other layer silently "
            "changes the FR4 — when the ESL went 100 → 10 µm the filler went "
            "246.4 → 264.4 µm. A fab stackup drawing would turn this into a "
            "real number (`design/NEEDED_INPUTS.md` §6).",
            "",
            "*Do not read the ESL⇄pad capacitance off this ordering.* Taken "
            "literally the table puts a 264 µm FR4 layer between the coverlay "
            "and the pad copper, because the guard-ring layer above the pads "
            "is placed first — and that layer has **zero** copper inside the "
            "active window, so the separation there is an artifact of the "
            "equal-division residual above, not geometry anyone measured. The "
            "response model instead takes the physically motivated adjacency "
            "for a resistive Micromegas: the ESL sits on the coverlay kapton, "
            "which is laminated straight onto the pads. That is the stack "
            "`response/solver/wpot.py` solves, and the ~19 µm of adhesive is "
            "29 % of the insulator it sees. The two models disagree here and "
            "the disagreement is unresolved; it does not matter for material "
            "budget (order barely matters for energy deposit) and it matters "
            "completely for the induced signal. The same missing fab drawing "
            "settles both.",
            "", END]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 3 if README.md's table is not what this emits")
    a = ap.parse_args()
    table = markdown(parse_spec(HEADER))
    if not a.check:
        print(table)
        return 0
    src = open(README).read()
    if BEGIN not in src or END not in src:
        print("FAIL: README.md has no generated-stack-table block")
        return 3
    cur = src[src.index(BEGIN):src.index(END) + len(END)]
    if cur.strip() == table.strip():
        print("README stack table is up to date with the geometry header.")
        return 0
    print("FAIL: README stack table has DRIFTED from "
          "shared/MX17ModuleGeometry.hh.\n"
          "Regenerate: python3 scripts/stack_table.py")
    return 3


if __name__ == "__main__":
    raise SystemExit(main())
